version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://backend.estheticsbyanna.net
    restart: unless-stopped